tpr to the server corrections

diff --git a/scripts/cl_dps/dpd-makedict b/scripts/cl_dps/dpd-makedict
--- a/scripts/cl_dps/dpd-makedict
+++ b/scripts/cl_dps/dpd-makedict
@@ -56,6 +56,19 @@ while true; do
     esac
 done
 
+# Ask the user if they want to attempt to mount the fileserver
+while true; do
+    echo -ne "\033[1;34m Do you want to attempt to mount the fileserver? \033[0m"
+    read mount_confirm
+    case $mount_confirm in
+        [Yy]* )
+            mnt
+            break;;
+        * )
+            break;;
+    esac
+done
+
 while true; do
     echo -ne "\033[1;34m copy DPD+SBS to the /Sharing between users/1 For Everyone/Software/Golden Dictionary/Default folder? \033[0m"
     read -n 1 -s user_input
@@ -84,6 +97,23 @@ while true; do
     case $user_input in
         [Yy]* )
             bash "${MASTER_SCRIPT}" "${LOG_BASE_NAME}" "${COMMAND_TO_EXECUTE_COPY_TPR[@]}"
+            break;;
+        * )
+            break;;
+    esac
+done
+
+# Ask the user if they want to attempt to umount the fileserver
+while true; do
+    echo -ne "\033[1;34m Do you want to umount the fileserver? \033[0m"
+    read -n 1 -s mount_confirm
+    if [[ $mount_confirm == "q" ]]; then
+        echo -e "\n\033[1;31m Aborted by user.\033[0m"
+        exit 1
+    fi
+    case $mount_confirm in
+        [Yy]* )
+            umnt
             break;;
         * )
             break;;
