various

diff --git a/scripts/cl_dps/dpd-makedict b/scripts/cl_dps/dpd-makedict
--- a/scripts/cl_dps/dpd-makedict
+++ b/scripts/cl_dps/dpd-makedict
@@ -12,12 +12,13 @@ LOG_BASE_NAME="make_dpd"
 TARGET_SCRIPT_PATH="${PROJECT_ROOT}/scripts/bash/make_dpd.sh"
 TARGET_SCRIPT_PATH_RU="${PROJECT_ROOT}/scripts/bash/make_ru_dpd.sh"
 TARGET_SCRIPT_PATH_COPY="${PROJECT_ROOT}/scripts/bash/copy_dpd_to_server"
-
+TARGET_SCRIPT_PATH_COPY_TPR="${PROJECT_ROOT}/scripts/moving/copy_dpd_for_classes.py"
 
 # The command to run, including 'uv run bash'
 COMMAND_TO_EXECUTE=(bash -c "cd '${PROJECT_ROOT}' && uv run bash '${TARGET_SCRIPT_PATH}'")
 COMMAND_TO_EXECUTE_RU=(bash -c "cd '${PROJECT_ROOT}' && uv run bash '${TARGET_SCRIPT_PATH_RU}'")
 COMMAND_TO_EXECUTE_COPY=(bash -c "cd '${PROJECT_ROOT}' && uv run bash '${TARGET_SCRIPT_PATH_COPY}'")
+COMMAND_TO_EXECUTE_COPY_TPR=(bash -c "cd '${PROJECT_ROOT}' && uv run python '${TARGET_SCRIPT_PATH_COPY_TPR}'")
 
 # Execute the master script
 
@@ -56,7 +57,7 @@ while true; do
 done
 
 while true; do
-    echo -ne "\033[1;34m copy to the server? \033[0m"
+    echo -ne "\033[1;34m copy DPD+SBS to the /Sharing between users/1 For Everyone/Software/Golden Dictionary/Default folder? \033[0m"
     read -n 1 -s user_input
     echo
     if [[ $user_input == "q" ]]; then
@@ -66,6 +67,23 @@ while true; do
     case $user_input in
         [Yy]* )
             bash "${MASTER_SCRIPT}" "${LOG_BASE_NAME}" "${COMMAND_TO_EXECUTE_COPY[@]}"
+            break;;
+        * )
+            break;;
+    esac
+done
+
+while true; do
+    echo -ne "\033[1;34m copy DPD + TPR for class to the /Sharing between users/For A. Devamitta/temp/ folder? \033[0m"
+    read -n 1 -s user_input
+    echo
+    if [[ $user_input == "q" ]]; then
+        echo -e "\n\033[1;31m Aborted by user.\033[0m"
+        exit 1
+    fi
+    case $user_input in
+        [Yy]* )
+            bash "${MASTER_SCRIPT}" "${LOG_BASE_NAME}" "${COMMAND_TO_EXECUTE_COPY_TPR[@]}"
             break;;
         * )
             break;;
